version: 2.1

jobs:
  build:
    docker:
     - image: cimg/base:2022.05
    resource_class: medium

    # would have been nice, but not for $2,000/month!
    # machine:
    #   image: ubuntu-2004-cuda-11.4:202110-01
    # resource_class: gpu.nvidia.small

    steps:
      - checkout

      # unit tests
      - run: pip install -r requirements.txt
      - run: pip install pytest pytest-cov
      - run: python -m pytest --cov=. --cov-report=xml --ignore=test.py

      # integration tests
      - run: sudo apt-get update
      - run: sudo apt install -yqq rsync
      - run: ./run_integration_tests_on_lambda.sh

      # deploy the image
      # - run: docker push company/app:$CIRCLE_BRANCH