version: 2.1

jobs:
  build:
    docker:
     - image: cimg/python:3.9-node
    resource_class: medium

    # would have been nice, but not for $2,000/month!
    # machine:
    #   image: ubuntu-2004-cuda-11.4:202110-01
    # resource_class: gpu.nvidia.small

    steps:
      - checkout

      - setup_remote_docker:
          docker_layer_caching: true

      - run: docker build -t gadicc/diffusers-api .

      # unit tests
      - run: docker run gadicc/diffusers-api conda run --no-capture -n xformers pytest --cov=. --cov-report=xml --ignore=diffusers

      # needed for later "apt install" steps
      - run: sudo apt-get update

      ## TODO.  The below was a great first step, but in future, let's build
      # the container on the host, run docker remotely on lambda, and
      # publish the same built image if tests pass.

      # disable temporary until semantic-release is all set up
      # also, should only run on main channel for releases (with sem-rel too)
      # integration tests
      # - run: sudo apt install -yqq rsync
      # - run: ./run_integration_tests_on_lambda.sh

      # deploy the image
      # - run: docker push company/app:$CIRCLE_BRANCH
      # https://github.com/semantic-release-plus/semantic-release-plus/tree/master/packages/plugins/docker
      - run:
          name: release
          command: |
            sudo apt-get install yarn
            yarn install
            yarn run semantic-release-plus